### ISSUE TITLE
Is Independant servers talking to public.pyzor.org:24441?

### ISSUE THREAD

**Issue by Isma399** [SpamExperts/pyzor#113]
### Version information
/usr/local/bin/pyzord 1.0.0

### Steps to replicate
Inbound server are in a private network (port forwarding from MX record IP)
So I install a pyzor server in DMZ, expecting it to talk to public.pyzor.org

Inbound servers send digest to pyzor server : 

`INFO anonymous,<INBOUND IP>,check,['1747e4e9004f1c815c3ad6761a3ce8a6b5f1f5b8'],200`

But I have no clue that pyzor server forwards this digest to public.pyzor.org
`tcpdump ip dst 5.9.124.53`
shows nothing

Firewall is open on port 24441 to the pyzor server.

Is this operation expected?
So pyzor checks from SpamAssassin on inbound servers will rely only on our digests?
Do I have to use this : 
`--forward-client-homedir=`

Thank for your reply

**Comment by tonyandrewmeyer** [comment]
Pyzor works over UDP, not TCP. If you do `pyzor ping` it should show which server(s) it connects to and the response. What do you get?

**Comment by Isma399** [comment]
Oups, I have forgotten that.
Here pyzor ping result from my pyzor server
`public.pyzor.org:24441  (200, 'OK')`
From my inbound server :
`<my pyzor server ip>:24441    (200, 'OK')`

I make an UDP capture on my pyzor, don't see anything between my pyzor server and public.pyzor.org

On my pyzor server, pyzor is called like that : 
`# ps aux |grep pyzor
root     16933  0.0  0.4 178080 16480 ?        Sl   11:43   0:00 /usr/bin/python3.6 /usr/local/bin/pyzord --detach /dev/null --homedir=/root/.pyzor/ --forward-client-homedir=/root/.pyzor/client/`

**Comment by Isma399** [comment]
Capture is made like that : 
```
tcpdump host  <INBOUND IP>  and proto 17
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

12:22:30.804368 IP inbound_ip.34064 > local_pyzor.24441: UDP, length 163
12:22:30.808118 IP local_pyzor..24441 > inbound_ip.34064: UDP, length 62
```

```
tcpdump host  5.9.124.53 and proto 17`
Nothing
```

**Comment by tonyandrewmeyer** [comment]
Ah, are you expecting your daemon to talk to the daemon at public.pyzor.org? Daemons serve locally. You can configure the client to connect to multiple daemons if you want to check against a local server as well as public.pyzor.org.

**Comment by Isma399** [comment]
OK, I didn't understand before.
It's OK for me that's daemon works locally.
Recieving around 200 000 mails daily, pyzor checks should be accurent.
Thank you very much for your answer and for this useful software.
