### ISSUE TITLE
Delist from Pyzor

### ISSUE THREAD

**Issue by Kuda-** [SpamExperts/pyzor#28]
Hello, I have an issue
Checking mail-tester.com shows me that I'm listed in Pyzor.
"PYZOR_CHECK Listed in Pyzor (http://pyzor.sf.net/)"

But I don't have the required information to complete the white list form. (http://public.pyzor.org/whitelist/)
I need the Pyzor digest, and Raw message. I don't have those, and I don't know where to find that information.

Is there anyone I could contact for help on this, or any way to get the required information?

**Comment by arminrahimian** [comment]
> 

I could not find any pyzor command to execute this command as you sent:
~$ pyzor digest < /tmp/1.eml
