### ISSUE TITLE
Is the licence "GPLv2 only" or "GPLv2 or later"

### ISSUE THREAD

**Issue by jasontibbitts** [SpamExperts/pyzor#35]
Fedora really cares about getting the licensing absolutely correct, and we'd like to know if the "any later version" clause in v2 of the GPL applies.  In an old version (0.5.0) usage.html seemed to indicate that this was the case, and Fedora had the license as "GPLv2 or later".  But usage.html is gone now, and the license section of the docs at http://pyzor.readthedocs.org/en/release-1-0-0/introduction.html#license seems to indicate "GPLv2 only".  I know it's minor, but could you clarify?

**Comment by alexkiro** [comment]
> But usage.html is gone now, and the license section of the docs at http://pyzor.readthedocs.org/en/release-1-0-0/introduction.html#license seems to indicate "GPLv2 only". I know it's minor, but could you clarify?

Thank you for the input! We've updated the documentation (http://www.pyzor.org/en/latest/introduction.html#license) to specify that redistributing can be done under GPLv2 only.

Please let us know if you would actually like to redistribute Pyzor under v3 instead.

**Comment by jasontibbitts** [comment]
Thanks for clarifying; I've made sure that's reflected in the Fedora package.

We have no desire to distribute the package under any particular license (as long as it's free, of course).  We just want to be absolutely clear about what that license is (because our legal team is extremely picky).
