### ISSUE TITLE
Whitelisting problem

### ISSUE THREAD

**Issue by squipa** [SpamExperts/pyzor#37]
My server is listed as spam on pyzor , when i try to whitelist it from your form it respond : Message not reported as spam. I don't now how to do that. What's wrong ?

Thanks

**Comment by squipa** [comment]
The ip of my server is : 37.59.1.24 .

Thanks a lot !

**Comment by alexkiro** [comment]
Pyzor does not list servers, but messages. If you want to whitelist a message you need to provide the raw message and pyzor digest. 

For more information on pyzor see the documentation (http://www.pyzor.org/en/latest/whitelist.html)
