### ISSUE TITLE
crash while parsing spam message

### ISSUE THREAD

**Issue by azhelev** [SpamExperts/pyzor#38]
Hi,

i got the following traceback while trying to check a message with pyzor.

$ pyzor -s mbox check < spam.mbox 
Traceback (most recent call last):
  File "/usr/bin/pyzor", line 408, in <module>
    main()
  File "/usr/bin/pyzor", line 152, in main
    if not dispatch(client, servers, config):
  File "/usr/bin/pyzor", line 237, in check
    for digested in get_input_handler(style):
  File "/usr/bin/pyzor", line 181, in _get_input_mbox
    tfile.write(sys.stdin.read().encode("utf8"))
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 2649: invalid start byte

I'm using pyzor 1.0.0 with python 3.4.3. I can provide the spam message that caused the crash if needed.

BR
Atanas

**Comment by alexkiro** [comment]
Thanks for the report! 

If you can provide the message that would be great. If you don't want to add it here, you can send it directly to me at `alex@alexkiro.com`

**Comment by azhelev** [comment]
Hi,
I've sent you an email, it looks like it's not possible to attach text files here, only photo attachments are supported.

**Comment by jasontibbitts** [comment]
I'm pretty sure this is the same issue: https://bugzilla.redhat.com/show_bug.cgi?id=1281859

There's a pretty good backtrace with the entire set of variables at https://bugzilla.redhat.com/attachment.cgi?id=1093717

I've asked the reporter if the actual message is available.  The backtrace does have the headers but not the body.

**Comment by jasontibbitts** [comment]
The reporter was kind enough to attach the complete message to the Fedora bug report.  You can get it here: https://bugzilla.redhat.com/attachment.cgi?id=1095581

**Comment by irreality177** [comment]
Verified manually.

Not reproducable on current version:
```
com:~$ pyzor -V
/usr/local/bin/pyzor 1.1.0
com:~$ pyzor -s mbox check < /root/1.mbx
public.pyzor.org:24441  (200, 'OK')     0       0
com:~$
```
But is reproducable on older one:
```
root@server1:~# pyzor -V
/usr/local/bin/pyzor 1.0.0
root@server1:~# pyzor -s mbox check < /root/1.mbx
Traceback (most recent call last):
  File "/usr/local/bin/pyzor", line 408, in <module>
    main()
  File "/usr/local/bin/pyzor", line 152, in main
    if not dispatch(client, servers, config):
  File "/usr/local/bin/pyzor", line 237, in check
    for digested in get_input_handler(style):
  File "/usr/local/bin/pyzor", line 181, in _get_input_mbox
    tfile.write(sys.stdin.read().encode("utf8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 2860: ordinal not in range(128)
```

I'll try to add the test for this.

**Comment by irreality177** [comment]
Test was added.

**Comment by alexkiro** [comment]
@irreality177 test is failing on python3 after d07509a4e562c1de73cc89a01ee53b9f46b219f1. Those need to be fixed before this is closed.

**Comment by irreality177** [comment]
Tests fixed.
