### ISSUE TITLE
Listed on Pyzor

### ISSUE THREAD

**Issue by thiagocpv** [SpamExperts/pyzor#39]
Hi there!

I don't know why I'm listed on Pyzor and I don't know how to remove. Please can you help me?
My domain is: upnetworks.com.br
I'm following this link: http://www.mail-tester.com/web-wb0iPJ
![image](https://cloud.githubusercontent.com/assets/3639439/8245340/54a97258-1603-11e5-957c-ef14f5d61a37.png)

Thanks

**Comment by tonyandrewmeyer** [comment]
Hi :).  Pyzor doesn't list people or IPs or domains.  It creates a unique hash of each message's content, and compares that to hashes that have been reported by other users.  So if you send a different message, you should have no issue.  If you're seeing false positives for a legitimate message, you can submit the message via the pyzor website, and we can whitelist it and fix any bugs as required.

**Comment by thiagocpv** [comment]
Hi @tonyandrewmeyer ,

How can I do it ? I don't have any digest and any messages about that. Just a test via mail-tester.com

Thanks.

**Comment by tonyandrewmeyer** [comment]
If you don't have any message, then there is nothing to whitelist.  Again, individual messages get 'listed', not domains or people.  If there is a website that is sending the same message all the time, then presumably someone reported that as spam.  You'll need to take that up with the website.  Pyzor doesn't have anything to do with mail-tester.com.

**Comment by thiagocpv** [comment]
Ok, I will talk with them soon.

Thank you very much.
