### ISSUE TITLE
Whitelist from website does not work?

### ISSUE THREAD

**Issue by Arkymedes** [SpamExperts/pyzor#42]
Hello,

Every single message coming from my server are being marked as "listed" on Pyzor.

Please find attached one of those emails that was sent using the https://www.mail-tester.com website.
[false-positive.txt](https://github.com/SpamExperts/pyzor/files/46322/false-positive.txt)

You can see the report here: https://www.mail-tester.com/web-1rRmDh

I installed Pyzor using Debian and followed your documentation to generate the digest of this email file.

`pyzor digest < false-positive.txt`
`a3917acbee3f33d744611512992355f721fdfdb7`

I then go to the formulary to whitelist it and the website reports "Digest does not match message."

Am I missing something obvious here?
Thank you in advance,

**Comment by tonyandrewmeyer** [comment]
Sorry about the slow reply.

What version of Pyzor are you using?  That's not the digest that I get with Pyzor 1.0.0:

    ~$ pyzor --version
    /usr/local/bin/pyzor 1.0.0
    ~$ pyzor digest < /tmp/false-positive.txt 
    a0f83d7e16b83e3ecc16e3267233f1b8f925c8e2

The message is primarily HTML boilerplate, which is generally not great.  Pyzor doesn't manage to completely strip it out:

    ~$ pyzor predigest < /tmp/false-positive.txt 
    /*Font*/
    453546324;}
    1552224324;}
    792.0pt;
    72.0pt72.0pt72.0pt;}
    gtemso9]><xml>

However, there are no reports for this content either:

    ~$ pyzor info < /tmp/false-positive.txt 
    public.pyzor.org:24441	(200, 'OK')
	Count: 0
	Entered: Thu Jan  1 01:00:00 1970
	Updated: Thu Jan  1 01:00:00 1970
	WL-Count: 0
	WL-Entered: Thu Jan  1 01:00:00 1970
	WL-Updated: Thu Jan  1 01:00:00 1970

So the message must actually be different in some way.  For the digest that you have there there are 129 spam reports and 0 non-spam reports.

    ~$ pyzor info --style=digests
    a3917acbee3f33d744611512992355f721fdfdb7
    public.pyzor.org:24441	(200, 'OK')
	Count: 129
	Entered: Sun Jan 12 22:43:39 2014
	Updated: Mon Nov  9 11:55:17 2015
	WL-Count: 0
	WL-Entered: Thu Jan  1 01:00:00 1970
	WL-Updated: Thu Jan  1 01:00:00 1970

I'm happy to whitelist this if I can verify that it is actually possible to generate this digest from a non-spam message.

**Comment by Arkymedes** [comment]
Hello there and thanks for your comprehensive reply!

I just tried another test: http://www.mail-tester.com/web-QD5TtV

My personal email
Subject: This is a test
Message: This is not SPAM :)

Same results :(

Weirdly enough, if I try to do anything with pyzor on my server, I get this:
```root@myserver:/# pyzor --version
Traceback (most recent call last):
  File "/usr/bin/pyzor", line 8, in <module>
    pyzor.client.run()
AttributeError: 'module' object has no attribute 'run'```

**Comment by bjquinn** [comment]
I'm having the same issue.  I'm running pyzor digest < /tmp/message.txt and I'm getting a digest of -- 

10e22b7d364b8b08c3e36f9df4afe7947be24c12

However, when I try to upload the file to http://public.pyzor.org/whitelist/, I get "digest does not match message".

[message.txt](https://github.com/SpamExperts/pyzor/files/54576/message.txt)

**Comment by tonyandrewmeyer** [comment]
FYI, the issue here appears to be that mail-tester.com is using a version of Pyzor from over 6 years ago, that isn't compatible with the whitelisting page that we have now.

We have reached out to them to see whether they are able to upgrade to a more modern version of Pyzor.

**Comment by bjquinn** [comment]
Thanks for the info.  Is the issue the same with public.pyzor.org/whitelist?

**Comment by alexkiro** [comment]
> FYI, the issue here appears to be that mail-tester.com is using a version of Pyzor from over 6 years ago, that isn't compatible with the whitelisting page that we have now.
> 
> We have reached out to them to see whether they are able to upgrade to a more modern version of Pyzor.

I just received confirmation that the guys from mail-tester have upgraded their version. This issue should be resolved now.

**Comment by shobray** [comment]
Hello,

This corporate mails is not flagged in pyzor whitelist.
Here is the test:
http://www.mail-tester.com/web-9r6cz&reloaded=2

I need the follow domains in whitelist: 

@umts.com.pt 
@newsumts.com.pt

The pyzor digest in raw messages files extensions *.txt  *.oft *.msg *.eml *.zip is getting the following message: 
"Digest does not match message."

Can someone help me?

Regards,
André Vaz
andre.vaz@umts.com.pt

**Comment by tonyandrewmeyer** [comment]
Pyzor matches message content. It has nothing to do with attachments or domains.
