### ISSUE TITLE
Delisting

### ISSUE THREAD

**Issue by Vilican** [SpamExperts/pyzor#43]
Sorry if this is the wrong place to ask.

I got in report that I am listed in Pyzor:
-1.985	PYZOR_CHECK	Listed in Pyzor (http://pyzor.sf.net/)

How can I request delisting?
I am lost in this technology.

**Comment by tonyandrewmeyer** [comment]
Pyzor lists messages, not people. If you have a message that is wrongly listed, then you can request whitelisting via the online tool: http://www.pyzor.org/en/release-1-0-0/whitelist.html
