### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_digest'

### ISSUE THREAD

**Issue by cleder** [SpamExperts/pyzor#45]
on http://pyzor.readthedocs.org/en/release-1-0-0/pyzor.client.html the documentation says:

```
>>> digest = pyzor.digest.get_digest(msg)
```

I get
      >>> import pyzor.digest
      >>> pyzor.digest.get_digest
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
      AttributeError: 'module' object has no attribute 'get_digest'

**Comment by alexkiro** [comment]
The documentation needs updating here. The new method of getting the digest is:

```python
>>> import pyzor.digest
>>> pyzor.digest.DataDigester(msg).value
'c3a8e8d987f07843792d2ab1823b04cc3cb87482'

```

**Comment by vmlellis** [comment]
When I execute this

``` python
>>> import pyzor.digest
>>> pyzor.digest.DataDigester(msg).value
```

I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vmlellis/.local/lib/python2.7/site-packages/pyzor/digest.py", line 82, in __init__
    for payload in self.digest_payloads(msg):
  File "/home/vmlellis/.local/lib/python2.7/site-packages/pyzor/digest.py", line 147, in digest_payloads
    for part in msg.walk():
AttributeError: 'str' object has no attribute 'walk'

**Comment by tonyandrewmeyer** [comment]
@vmlellis is your msg an email.message.Message object?  It looks like it's a string.  If you want to convert a string in RFC 5322 format to email.message.Message you can use email.message_from_string (see the [standard library documentation](https://docs.python.org/2/library/email.html) for more details).

**Comment by noqqe** [comment]
Spent half an hour looking for this. 
Please update documentation. Half a year is way too long for this simple but needed update.

**Comment by lasley** [comment]
Updated in #60

**Comment by alexkiro** [comment]
Thanks for the pull request: :+1:

**Comment by lasley** [comment]
Nah, thanks for the badass library 👍
