### ISSUE TITLE
Use python-future for 2 and 3 Python compatibility

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/pyzor#46]
Right now the Pyzor code is compatible with both Python 2 and Python 3 but only if the the code is converted with 2to3 first. When installing using pip this is done automatically, however it would be better to just use python-future for this and so no conversion will be required.

**Comment by alexkiro** [comment]
Latest build is [passing](https://travis-ci.org/SpamExperts/pyzor/builds/102568794)

**Comment by GabiSL** [comment]
Verified - Passed!
