### ISSUE TITLE
White list content "test"

### ISSUE THREAD

**Issue by bokanist** [SpamExperts/pyzor#48]
This is not really an issue.

But it's the tenth time a customer tells me "the mail server is not properly configured" because they send a message to mail-tester.com with just "test" in the content.

Maybe it would be nice to whitelist this content.

**Comment by tonyandrewmeyer** [comment]
Please submit whitelist requests via http://public.pyzor.org/whitelist/

Note that mail-tester.com were using a very old version until recently, which was causing issues for them. They've told us they have updated now.
