### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by egorsmkv** [SpamExperts/pyzor#54]
Hello.

Please add new release to https://github.com/SpamExperts/pyzor/releases.

**Comment by tonyandrewmeyer** [comment]
1.0 is still the latest release. Are you asking for a new release based on current master? There aren't really significant changes. Is there something in particular that you're needing?

**Comment by egorsmkv** [comment]
This stability : ) I think you forgot to update the version there.

**Comment by crhalpin** [comment]
I maintain the FreeBSD port for pyzor. A user is reporting that 1.1.1 works significantly better than 1.0.0 in their environment for non-utf-8 mail and asking about updating the port. I prefer to keep my ports at released versions whenever I can. Would it be possible to get a new pyzor release?

**Comment by orlitzky** [comment]
The Gentoo python team is pushing for removal of pyzor: https://archives.gentoo.org/gentoo-dev-announce/message/55b938a8074b7a6cef204f7206758b74

The 1.0.0 release doesn't work with python3. I've been hacking it for years trying to keep it working, but it's too much work. Please just release a new version with the accumulated changes so I can update the version and save it from removal.

**Comment by hydrapolic** [comment]
> The Gentoo python team is pushing for removal of pyzor: https://archives.gentoo.org/gentoo-dev-announce/message/55b938a8074b7a6cef204f7206758b74
> 
> The 1.0.0 release doesn't work with python3. I've been hacking it for years trying to keep it working, but it's too much work. Please just release a new version with the accumulated changes so I can update the version and save it from removal.

As a Gentoo user I can just double this request. Pretty please.

**Comment by mimi89999** [comment]
I'm also a Gentoo user using pyzor. It would be really sad to see pyzor removed from Gentoo.

@tonyandrewmeyer Could you please make a new release? Is there anything blocking that?

**Comment by pallas** [comment]
```!!! The following installed packages are masked:
- mail-filter/pyzor-1.0.0-r1::gentoo (masked by: package.mask)
/usr/portage/profiles/package.mask:
# Michael Orlitzky <mjo@gentoo.org> (2020-04-19)
# Stuck on Python 3.6, support for which already required
# backporting patches to a release from 2014. Upstream's git
# HEAD works fine, but they can't be bothered to make a new
# release. Bug 718326. Removal whenever it becomes an issue.

**Comment by hydrapolic** [comment]
Even a new tag would be sufficient (at least for Gentoo Linux).

**Comment by matthijskooijman** [comment]
> The 1.0.0 release doesn't work with python3. I've been hacking it for years trying to keep it working, but it's too much work. Please just release a new version with the accumulated changes so I can update the version and save it from removal.

This does not seem right. The [discussion](https://archives.gentoo.org/gentoo-dev-announce/message/55b938a8074b7a6cef204f7206758b74) you linked says gentoo will remove it for not supporting Python 3.7 apparently, so python3 is certainly supported (Debian also runs pyzor on py3).


> A user is reporting that 1.1.1 works significantly better than 1.0.0 in their environment for non-utf-8 mail and asking about updating the port. I prefer to keep my ports at released versions whenever I can. Would it be possible to get a new pyzor release?

I also came here looking for fixes for utf-8 decoding errors (in particular, #64 and #74 which are both fixed in master, but broken in Debian and Ubuntu, for which a release would help).

**Comment by hydrapolic** [comment]
> > The 1.0.0 release doesn't work with python3. I've been hacking it for years trying to keep it working, but it's too much work. Please just release a new version with the accumulated changes so I can update the version and save it from removal.
> 
> This does not seem right. The [discussion](https://archives.gentoo.org/gentoo-dev-announce/message/55b938a8074b7a6cef204f7206758b74) you linked says gentoo will remove it for not supporting Python 3.7 apparently, so python3 is certainly supported (Debian also runs pyzor on py3).
> 

Michael added some patches to make it working at least with Python 3.6. But if you'd take the vanilla 1.0.0 release then it simply wouldn't work.

**Comment by orlitzky** [comment]
Our existing version probably works with python-3.7, too, but the easy way to check (run the test suite) also requires a massive backporting effort to get off the ground. All of that effort is both duplicated (by every distro) and outright wasted because the fifteen minutes it would take to make a release could easily prevent it.

**Comment by pallas** [comment]
This is now breaking on Gentoo, since 3.7 is the target default.

**Comment by ametzler** [comment]
Looks like this was closed by mistake.  There is no release on either https://github.com/SpamExperts/pyzor/releases or https://github.com/SpamExperts/pyzor/tags or https://pypi.org/project/pyzor/#files - Please reopen.

cu Andreas

**Comment by egorsmkv** [comment]
@ametzler I don't think this issue will be resolved.

**Comment by egorsmkv** [comment]
I suggest you to fork the project

**Comment by egorsmkv** [comment]
How can we get this issue to be resolved if the maintainers don’t reply?Sent from my iPhoneOn 14 Nov 2022, at 20:19, Benjamin Neff ***@***.***> wrote:﻿
But we still need a new release, so it should be reopened.

**Comment by ametzler** [comment]
@egorsmkv wrote
> @ametzler I don't think this issue will be resolved.

Even if it is not resolved now the open bug report is not without use. It documents that the project is not as dead as the latest release makes it look. And if the maintainers reapppear they will have it on their TODO list.

cu Andreas
