### ISSUE TITLE
documentation: procmail recipes not adequately presented

### ISSUE THREAD

**Issue by natmaka** [SpamExperts/pyzor#63]
Tthe 2 procmail recipes published at http://www.pyzor.org/en/release-1-0-0/procmail.html are not formated adequately.

In each recipe a "\n" is missing

Example:

     :0 Wc
    | pyzor check :0 a
    pyzor-caught

Should be:

    :0 Wc
    | pyzor check
    :0 a
    pyzor-caught

**Comment by kubbity** [comment]
Fixed on [latest](https://pyzor.readthedocs.io/en/latest/procmail.html).
