### ISSUE TITLE
Mail server in blacklist pyzor

### ISSUE THREAD

**Issue by mauro130** [SpamExperts/pyzor#67]
our mail server is on a blacklist, please verify that we urgently we need this procedure.
We have requested many times to whitelist our domain, please confirm our domain is ok because in tester like  mail-tester.com it shows:

-1.985		PYZOR_CHECK

Please your urgent help.

**Comment by tonyandrewmeyer** [comment]
Pyzor does not blacklist domains. It is a message fingerprinting system.

If you are having trouble with mail-tester.com, please contact them for assistance.
